// Shade catalog shown on the picker step.
//
// `colorDescription` is fed verbatim into the Gemini prompt, so it stays in
// English; `nameFa` is what the UI renders.
//
// `path` decides how the recolor runs: dark targets can be done on-device with
// the MediaPipe segmenter, light ones need Gemini to simulate bleaching.
//
// NOTE: `brand` is a PLACEHOLDER split (dark → Bianca, light → Oyster) so the
// brand filter on the landing page has something to filter. Replace it with the
// real per-shade brand once the two catalogs are supplied.

export type ShadePath = "local" | "ai";
export type Brand = "bianca" | "oyster" | "perlacolor";

export type ShadeInfo = {
  shadeCode: string;
  shadeName: string;
  /** Persian display name. Absent for shades read off a box by Gemini. */
  nameFa?: string;
  hexColor: string;
  /** English, prompt-facing. */
  colorDescription: string;
  confidence: "high" | "medium" | "low";
};

export type PresetShade = ShadeInfo & {
  path: ShadePath;
  brand: Brand;
  /** Persian label for the chart family this shade sits in. */
  family: string;
};

export const BRAND_LABEL: Record<Brand, string> = {
  bianca: "بیانکا",
  oyster: "اویستر",
  perlacolor: "پرلاکالر",
};

/** Tab order on the shade picker. */
export const BRANDS: Brand[] = ["perlacolor", "bianca", "oyster"];

export const PRESET_SHADES: PresetShade[] = [
  // Dark shades → local canvas recolor
  { shadeCode: "1/0",  shadeName: "Natural Black",       nameFa: "مشکی طبیعی",                hexColor: "#0D0905", colorDescription: "pure natural black, cool neutral undertones",                  confidence: "high", path: "local", brand: "bianca", family: "رنگ‌های تیره" },
  { shadeCode: "2/0",  shadeName: "Darkest Brown",       nameFa: "قهوه‌ای خیلی تیره",          hexColor: "#1A0E08", colorDescription: "near-black darkest brown, neutral cool undertones",            confidence: "high", path: "local", brand: "bianca", family: "رنگ‌های تیره" },
  { shadeCode: "3/0",  shadeName: "Dark Brown",          nameFa: "قهوه‌ای تیره",               hexColor: "#2C1A0E", colorDescription: "deep dark brown, cool undertones",                             confidence: "high", path: "local", brand: "bianca", family: "رنگ‌های تیره" },
  { shadeCode: "3/3",  shadeName: "Dark Golden Brown",   nameFa: "قهوه‌ای تیره طلایی",         hexColor: "#4A2A10", colorDescription: "dark brown with warm golden reflect",                          confidence: "high", path: "local", brand: "bianca", family: "رنگ‌های تیره" },
  { shadeCode: "3/66", shadeName: "Dark Intense Red",    nameFa: "قرمز پرقدرت تیره",           hexColor: "#6B1510", colorDescription: "dark brown with very intense red-violet reflect",              confidence: "high", path: "local", brand: "bianca", family: "رنگ‌های تیره" },
  { shadeCode: "4/0",  shadeName: "Medium Brown",        nameFa: "قهوه‌ای متوسط",              hexColor: "#5C3520", colorDescription: "neutral medium brown, natural finish",                         confidence: "high", path: "local", brand: "bianca", family: "رنگ‌های تیره" },
  { shadeCode: "4/4",  shadeName: "Medium Copper",       nameFa: "مسی متوسط",                  hexColor: "#8B4015", colorDescription: "medium brown with warm copper-orange reflect, vibrant",        confidence: "high", path: "local", brand: "bianca", family: "رنگ‌های تیره" },
  { shadeCode: "4/6",  shadeName: "Red Chestnut",        nameFa: "شاه‌بلوطی قرمز",             hexColor: "#8B3520", colorDescription: "warm medium brown with intense red undertones, glossy finish", confidence: "high", path: "local", brand: "bianca", family: "رنگ‌های تیره" },
  { shadeCode: "5/0",  shadeName: "Light Brown",         nameFa: "قهوه‌ای روشن",               hexColor: "#7A5030", colorDescription: "natural light brown, balanced warm-neutral tone",              confidence: "high", path: "local", brand: "bianca", family: "رنگ‌های تیره" },
  { shadeCode: "5/3",  shadeName: "Light Golden Brown",  nameFa: "قهوه‌ای روشن طلایی",         hexColor: "#8B6535", colorDescription: "light brown with warm golden and caramel tones",               confidence: "high", path: "local", brand: "bianca", family: "رنگ‌های تیره" },
  { shadeCode: "5/5",  shadeName: "Light Mahogany",      nameFa: "ماهاگونی روشن",              hexColor: "#7B3F30", colorDescription: "warm light brown with mahogany-red reflect",                   confidence: "high", path: "local", brand: "bianca", family: "رنگ‌های تیره" },
  { shadeCode: "6/0",  shadeName: "Dark Blonde",         nameFa: "بلوند تیره",                 hexColor: "#9A7540", colorDescription: "dark blonde, natural warm tone, subtle golden reflect",        confidence: "high", path: "local", brand: "bianca", family: "رنگ‌های تیره" },
  { shadeCode: "6/1",  shadeName: "Dark Ash Blonde",     nameFa: "بلوند تیره خاکستری",         hexColor: "#7A6A55", colorDescription: "dark blonde with cool ash undertones, matte finish",           confidence: "high", path: "local", brand: "bianca", family: "رنگ‌های تیره" },
  // Light shades → Gemini AI recolor
  { shadeCode: "7/0",  shadeName: "Medium Blonde",       nameFa: "بلوند متوسط",                hexColor: "#C8A040", colorDescription: "medium natural blonde, warm balanced tone",                    confidence: "high", path: "ai", brand: "oyster", family: "رنگ‌های روشن" },
  { shadeCode: "7/1",  shadeName: "Medium Ash Blonde",   nameFa: "بلوند متوسط خاکستری",        hexColor: "#B8A870", colorDescription: "medium blonde with cool ash undertones, pearl effect",         confidence: "high", path: "ai", brand: "oyster", family: "رنگ‌های روشن" },
  { shadeCode: "7/3",  shadeName: "Medium Gold Blonde",  nameFa: "بلوند متوسط طلایی",          hexColor: "#BF9040", colorDescription: "medium warm blonde with golden honey tones",                   confidence: "high", path: "ai", brand: "oyster", family: "رنگ‌های روشن" },
  { shadeCode: "7/44", shadeName: "Medium Copper Blonde",nameFa: "بلوند متوسط مسی",            hexColor: "#C86830", colorDescription: "medium blonde with intense warm copper-orange reflect",        confidence: "high", path: "ai", brand: "oyster", family: "رنگ‌های روشن" },
  { shadeCode: "8/0",  shadeName: "Light Blonde",        nameFa: "بلوند روشن",                 hexColor: "#D4B060", colorDescription: "light natural blonde, warm luminous tone",                     confidence: "high", path: "ai", brand: "oyster", family: "رنگ‌های روشن" },
  { shadeCode: "8/1",  shadeName: "Light Ash Blonde",    nameFa: "بلوند روشن خاکستری",         hexColor: "#D0C085", colorDescription: "light blonde with cool ash undertones, sophisticated finish",  confidence: "high", path: "ai", brand: "oyster", family: "رنگ‌های روشن" },
  { shadeCode: "8/3",  shadeName: "Light Gold Blonde",   nameFa: "بلوند روشن طلایی",           hexColor: "#D4A855", colorDescription: "light warm blonde with golden highlights, sun-kissed",         confidence: "high", path: "ai", brand: "oyster", family: "رنگ‌های روشن" },
  { shadeCode: "9/1",  shadeName: "Very Light Ash",      nameFa: "بلوند خیلی روشن خاکستری",    hexColor: "#DDD0A0", colorDescription: "very light cool blonde, ash undertones, pearl finish",         confidence: "high", path: "ai", brand: "oyster", family: "رنگ‌های روشن" },
  { shadeCode: "9/3",  shadeName: "Very Light Golden",   nameFa: "بلوند خیلی روشن طلایی",      hexColor: "#E2C87A", colorDescription: "very light warm blonde with golden shimmer",                   confidence: "high", path: "ai", brand: "oyster", family: "رنگ‌های روشن" },
  { shadeCode: "10/01",shadeName: "Platinum Blonde",     nameFa: "بلوند پلاتینی",              hexColor: "#EFE5CA", colorDescription: "lightest platinum blonde, icy cool tone, high-shine finish",   confidence: "high", path: "ai", brand: "oyster", family: "رنگ‌های روشن" },

  // ── Perlacolor ──────────────────────────────────────────────────────────
  // Shade codes and family names transcribed from the printed Perlacolor
  // fold-out chart. The hex values are DERIVED from the level/tone system
  // (level sets lightness, the reflect after the slash sets hue/saturation)
  // rather than sampled from the print, so they read as a coherent ramp but
  // are approximations — tune any that look off against the physical chart.
  // The Mixtones row is deliberately excluded: those are correctors mixed
  // into another shade, not shades you would preview on hair.
  { shadeCode: "1/0",    shadeName: "Black Natural",                   nameFa: "مشکی طبیعی",                      hexColor: "#0D0B0A", colorDescription: "black base with neutral natural base, balanced warm-cool undertones",                       confidence: "high", path: "local",  brand: "perlacolor", family: "طبیعی" },
  { shadeCode: "3/0",    shadeName: "Dark Brown Natural",              nameFa: "قهوه‌ای تیره طبیعی",              hexColor: "#2F1D0E", colorDescription: "dark brown base with neutral natural base, balanced warm-cool undertones",                  confidence: "high", path: "local",  brand: "perlacolor", family: "طبیعی" },
  { shadeCode: "4/0",    shadeName: "Brown Natural",                   nameFa: "قهوه‌ای طبیعی",                   hexColor: "#4E3118", colorDescription: "brown base with neutral natural base, balanced warm-cool undertones",                       confidence: "high", path: "local",  brand: "perlacolor", family: "طبیعی" },
  { shadeCode: "5/0",    shadeName: "Light Brown Natural",             nameFa: "قهوه‌ای روشن طبیعی",              hexColor: "#6D4827", colorDescription: "light brown base with neutral natural base, balanced warm-cool undertones",                 confidence: "high", path: "local",  brand: "perlacolor", family: "طبیعی" },
  { shadeCode: "6/0",    shadeName: "Dark Blonde Natural",             nameFa: "بلوند تیره طبیعی",                hexColor: "#865C37", colorDescription: "dark blonde base with neutral natural base, balanced warm-cool undertones",                 confidence: "high", path: "local",  brand: "perlacolor", family: "طبیعی" },
  { shadeCode: "7/0",    shadeName: "Blonde Natural",                  nameFa: "بلوند طبیعی",                     hexColor: "#A4754C", colorDescription: "blonde base with neutral natural base, balanced warm-cool undertones",                      confidence: "high", path: "ai",     brand: "perlacolor", family: "طبیعی" },
  { shadeCode: "8/0",    shadeName: "Light Blonde Natural",            nameFa: "بلوند روشن طبیعی",                hexColor: "#B69272", colorDescription: "light blonde base with neutral natural base, balanced warm-cool undertones",                confidence: "high", path: "ai",     brand: "perlacolor", family: "طبیعی" },
  { shadeCode: "9/0",    shadeName: "Very Light Blonde Natural",       nameFa: "بلوند خیلی روشن طبیعی",           hexColor: "#C4AC97", colorDescription: "very light blonde base with neutral natural base, balanced warm-cool undertones",           confidence: "high", path: "ai",     brand: "perlacolor", family: "طبیعی" },
  { shadeCode: "10/0",   shadeName: "Platinum Blonde Natural",         nameFa: "بلوند پلاتینی طبیعی",             hexColor: "#D4C6B9", colorDescription: "platinum blonde base with neutral natural base, balanced warm-cool undertones",             confidence: "high", path: "ai",     brand: "perlacolor", family: "طبیعی" },
  { shadeCode: "3/00",   shadeName: "Dark Brown Intense Natural",      nameFa: "قهوه‌ای تیره طبیعی پرقدرت",       hexColor: "#29180A", colorDescription: "dark brown base with deep intense natural base with strong pigment coverage",               confidence: "high", path: "local",  brand: "perlacolor", family: "طبیعی پرقدرت" },
  { shadeCode: "4/00",   shadeName: "Brown Intense Natural",           nameFa: "قهوه‌ای طبیعی پرقدرت",            hexColor: "#492C13", colorDescription: "brown base with deep intense natural base with strong pigment coverage",                    confidence: "high", path: "local",  brand: "perlacolor", family: "طبیعی پرقدرت" },
  { shadeCode: "5/00",   shadeName: "Light Brown Intense Natural",     nameFa: "قهوه‌ای روشن طبیعی پرقدرت",       hexColor: "#694221", colorDescription: "light brown base with deep intense natural base with strong pigment coverage",              confidence: "high", path: "local",  brand: "perlacolor", family: "طبیعی پرقدرت" },
  { shadeCode: "6/00",   shadeName: "Dark Blonde Intense Natural",     nameFa: "بلوند تیره طبیعی پرقدرت",         hexColor: "#83562F", colorDescription: "dark blonde base with deep intense natural base with strong pigment coverage",              confidence: "high", path: "local",  brand: "perlacolor", family: "طبیعی پرقدرت" },
  { shadeCode: "7/00",   shadeName: "Blonde Intense Natural",          nameFa: "بلوند طبیعی پرقدرت",              hexColor: "#A27043", colorDescription: "blonde base with deep intense natural base with strong pigment coverage",                   confidence: "high", path: "ai",     brand: "perlacolor", family: "طبیعی پرقدرت" },
  { shadeCode: "8/00",   shadeName: "Light Blonde Intense Natural",    nameFa: "بلوند روشن طبیعی پرقدرت",         hexColor: "#B78C67", colorDescription: "light blonde base with deep intense natural base with strong pigment coverage",             confidence: "high", path: "ai",     brand: "perlacolor", family: "طبیعی پرقدرت" },
  { shadeCode: "9/00",   shadeName: "Very Light Blonde Intense Natural", nameFa: "بلوند خیلی روشن طبیعی پرقدرت",    hexColor: "#C3A68D", colorDescription: "very light blonde base with deep intense natural base with strong pigment coverage",        confidence: "high", path: "ai",     brand: "perlacolor", family: "طبیعی پرقدرت" },
  { shadeCode: "10/00",  shadeName: "Platinum Blonde Intense Natural", nameFa: "بلوند پلاتینی طبیعی پرقدرت",      hexColor: "#D2C1B1", colorDescription: "platinum blonde base with deep intense natural base with strong pigment coverage",          confidence: "high", path: "ai",     brand: "perlacolor", family: "طبیعی پرقدرت" },
  { shadeCode: "1/1",    shadeName: "Blue Black",                      nameFa: "مشکی آبی",                        hexColor: "#0D1119", colorDescription: "blue-black, cool deep blue reflect over a black base",                                      confidence: "high", path: "local",  brand: "perlacolor", family: "خاکستری" },
  { shadeCode: "5/1",    shadeName: "Light Brown Ash",                 nameFa: "قهوه‌ای روشن خاکستری",            hexColor: "#574E42", colorDescription: "light brown base with cool ash reflect, neutralises warmth, matte finish",                  confidence: "high", path: "local",  brand: "perlacolor", family: "خاکستری" },
  { shadeCode: "6/1",    shadeName: "Dark Blonde Ash",                 nameFa: "بلوند تیره خاکستری",              hexColor: "#6D6355", colorDescription: "dark blonde base with cool ash reflect, neutralises warmth, matte finish",                  confidence: "high", path: "local",  brand: "perlacolor", family: "خاکستری" },
  { shadeCode: "7/1",    shadeName: "Blonde Ash",                      nameFa: "بلوند خاکستری",                   hexColor: "#887D6C", colorDescription: "blonde base with cool ash reflect, neutralises warmth, matte finish",                       confidence: "high", path: "ai",     brand: "perlacolor", family: "خاکستری" },
  { shadeCode: "8/1",    shadeName: "Light Blonde Ash",                nameFa: "بلوند روشن خاکستری",              hexColor: "#A2988B", colorDescription: "light blonde base with cool ash reflect, neutralises warmth, matte finish",                 confidence: "high", path: "ai",     brand: "perlacolor", family: "خاکستری" },
  { shadeCode: "9/1",    shadeName: "Very Light Blonde Ash",           nameFa: "بلوند خیلی روشن خاکستری",         hexColor: "#B8B1A8", colorDescription: "very light blonde base with cool ash reflect, neutralises warmth, matte finish",            confidence: "high", path: "ai",     brand: "perlacolor", family: "خاکستری" },
  { shadeCode: "10/1",   shadeName: "Platinum Blonde Ash",             nameFa: "بلوند پلاتینی خاکستری",           hexColor: "#CECAC5", colorDescription: "platinum blonde base with cool ash reflect, neutralises warmth, matte finish",              confidence: "high", path: "ai",     brand: "perlacolor", family: "خاکستری" },
  { shadeCode: "5/11",   shadeName: "Light Brown Matt Ash",            nameFa: "قهوه‌ای روشن مات",                hexColor: "#514D43", colorDescription: "light brown base with intense matt ash reflect, strongly anti-orange, muted finish",        confidence: "high", path: "local",  brand: "perlacolor", family: "مات" },
  { shadeCode: "6/11",   shadeName: "Dark Blonde Matt Ash",            nameFa: "بلوند تیره مات",                  hexColor: "#676356", colorDescription: "dark blonde base with intense matt ash reflect, strongly anti-orange, muted finish",        confidence: "high", path: "local",  brand: "perlacolor", family: "مات" },
  { shadeCode: "7/11",   shadeName: "Blonde Matt Ash",                 nameFa: "بلوند مات",                       hexColor: "#827D6E", colorDescription: "blonde base with intense matt ash reflect, strongly anti-orange, muted finish",             confidence: "high", path: "ai",     brand: "perlacolor", family: "مات" },
  { shadeCode: "8/11",   shadeName: "Light Blonde Matt Ash",           nameFa: "بلوند روشن مات",                  hexColor: "#9C988C", colorDescription: "light blonde base with intense matt ash reflect, strongly anti-orange, muted finish",       confidence: "high", path: "ai",     brand: "perlacolor", family: "مات" },
  { shadeCode: "9/11",   shadeName: "Very Light Blonde Matt Ash",      nameFa: "بلوند خیلی روشن مات",             hexColor: "#B3B0A8", colorDescription: "very light blonde base with intense matt ash reflect, strongly anti-orange, muted finish",  confidence: "high", path: "ai",     brand: "perlacolor", family: "مات" },
  { shadeCode: "10/11",  shadeName: "Platinum Blonde Matt Ash",        nameFa: "بلوند پلاتینی مات",               hexColor: "#CAC9C3", colorDescription: "platinum blonde base with intense matt ash reflect, strongly anti-orange, muted finish",    confidence: "high", path: "ai",     brand: "perlacolor", family: "مات" },
  { shadeCode: "8/9",    shadeName: "Light Blonde Pearl",              nameFa: "بلوند روشن صدفی",                 hexColor: "#A99C8E", colorDescription: "light blonde base with soft pearlescent reflect, luminous cool shimmer",                    confidence: "high", path: "ai",     brand: "perlacolor", family: "صدفی" },
  { shadeCode: "9/9",    shadeName: "Very Light Blonde Pearl",         nameFa: "بلوند خیلی روشن صدفی",            hexColor: "#BEB5AC", colorDescription: "very light blonde base with soft pearlescent reflect, luminous cool shimmer",               confidence: "high", path: "ai",     brand: "perlacolor", family: "صدفی" },
  { shadeCode: "10/9",   shadeName: "Platinum Blonde Pearl",           nameFa: "بلوند پلاتینی صدفی",              hexColor: "#D4CFC9", colorDescription: "platinum blonde base with soft pearlescent reflect, luminous cool shimmer",                 confidence: "high", path: "ai",     brand: "perlacolor", family: "صدفی" },
  { shadeCode: "8/31",   shadeName: "Light Blonde Sand",               nameFa: "بلوند روشن شنی",                  hexColor: "#B2A080", colorDescription: "light blonde base with sandy beige reflect, gold softened by ash",                          confidence: "high", path: "ai",     brand: "perlacolor", family: "شنی" },
  { shadeCode: "9/31",   shadeName: "Very Light Blonde Sand",          nameFa: "بلوند خیلی روشن شنی",             hexColor: "#C4B7A1", colorDescription: "very light blonde base with sandy beige reflect, gold softened by ash",                     confidence: "high", path: "ai",     brand: "perlacolor", family: "شنی" },
  { shadeCode: "10/31",  shadeName: "Platinum Blonde Sand",            nameFa: "بلوند پلاتینی شنی",               hexColor: "#D6CFC2", colorDescription: "platinum blonde base with sandy beige reflect, gold softened by ash",                       confidence: "high", path: "ai",     brand: "perlacolor", family: "شنی" },
  { shadeCode: "4/3",    shadeName: "Brown Golden",                    nameFa: "قهوه‌ای طلایی",                   hexColor: "#533913", colorDescription: "brown base with warm golden reflect, honeyed glow",                                         confidence: "high", path: "local",  brand: "perlacolor", family: "طلایی" },
  { shadeCode: "5/3",    shadeName: "Light Brown Golden",              nameFa: "قهوه‌ای روشن طلایی",              hexColor: "#78531C", colorDescription: "light brown base with warm golden reflect, honeyed glow",                                   confidence: "high", path: "local",  brand: "perlacolor", family: "طلایی" },
  { shadeCode: "6/3",    shadeName: "Dark Blonde Golden",              nameFa: "بلوند تیره طلایی",                hexColor: "#996A24", colorDescription: "dark blonde base with warm golden reflect, honeyed glow",                                   confidence: "high", path: "local",  brand: "perlacolor", family: "طلایی" },
  { shadeCode: "7/3",    shadeName: "Blonde Golden",                   nameFa: "بلوند طلایی",                     hexColor: "#C08630", colorDescription: "blonde base with warm golden reflect, honeyed glow",                                        confidence: "high", path: "ai",     brand: "perlacolor", family: "طلایی" },
  { shadeCode: "8/3",    shadeName: "Light Blonde Golden",             nameFa: "بلوند روشن طلایی",                hexColor: "#D2A055", colorDescription: "light blonde base with warm golden reflect, honeyed glow",                                  confidence: "high", path: "ai",     brand: "perlacolor", family: "طلایی" },
  { shadeCode: "9/3",    shadeName: "Very Light Blonde Golden",        nameFa: "بلوند خیلی روشن طلایی",           hexColor: "#DBB77F", colorDescription: "very light blonde base with warm golden reflect, honeyed glow",                             confidence: "high", path: "ai",     brand: "perlacolor", family: "طلایی" },
  { shadeCode: "10/3",   shadeName: "Platinum Blonde Golden",          nameFa: "بلوند پلاتینی طلایی",             hexColor: "#E6CDA8", colorDescription: "platinum blonde base with warm golden reflect, honeyed glow",                               confidence: "high", path: "ai",     brand: "perlacolor", family: "طلایی" },
  { shadeCode: "7/33",   shadeName: "Blonde Intense Golden",           nameFa: "بلوند طلایی پرقدرت",              hexColor: "#D3901D", colorDescription: "blonde base with vivid intense golden reflect, rich saturated warmth",                      confidence: "high", path: "ai",     brand: "perlacolor", family: "طلایی پرقدرت" },
  { shadeCode: "8/33",   shadeName: "Light Blonde Intense Golden",     nameFa: "بلوند روشن طلایی پرقدرت",         hexColor: "#E2A945", colorDescription: "light blonde base with vivid intense golden reflect, rich saturated warmth",                confidence: "high", path: "ai",     brand: "perlacolor", family: "طلایی پرقدرت" },
  { shadeCode: "9/33",   shadeName: "Very Light Blonde Intense Golden", nameFa: "بلوند خیلی روشن طلایی پرقدرت",    hexColor: "#E7BD73", colorDescription: "very light blonde base with vivid intense golden reflect, rich saturated warmth",           confidence: "high", path: "ai",     brand: "perlacolor", family: "طلایی پرقدرت" },
  { shadeCode: "4/8",    shadeName: "Brown Tobacco",                   nameFa: "قهوه‌ای تنباکویی",                hexColor: "#482F19", colorDescription: "brown base with warm tobacco-beige reflect, soft dusty warmth",                             confidence: "high", path: "local",  brand: "perlacolor", family: "تنباکویی" },
  { shadeCode: "5/8",    shadeName: "Light Brown Tobacco",             nameFa: "قهوه‌ای روشن تنباکویی",           hexColor: "#684527", colorDescription: "light brown base with warm tobacco-beige reflect, soft dusty warmth",                       confidence: "high", path: "local",  brand: "perlacolor", family: "تنباکویی" },
  { shadeCode: "6/8",    shadeName: "Dark Blonde Tobacco",             nameFa: "بلوند تیره تنباکویی",             hexColor: "#835935", colorDescription: "dark blonde base with warm tobacco-beige reflect, soft dusty warmth",                       confidence: "high", path: "local",  brand: "perlacolor", family: "تنباکویی" },
  { shadeCode: "7/8",    shadeName: "Blonde Tobacco",                  nameFa: "بلوند تنباکویی",                  hexColor: "#A37247", colorDescription: "blonde base with warm tobacco-beige reflect, soft dusty warmth",                            confidence: "high", path: "ai",     brand: "perlacolor", family: "تنباکویی" },
  { shadeCode: "8/8",    shadeName: "Light Blonde Tobacco",            nameFa: "بلوند روشن تنباکویی",             hexColor: "#B98F69", colorDescription: "light blonde base with warm tobacco-beige reflect, soft dusty warmth",                      confidence: "high", path: "ai",     brand: "perlacolor", family: "تنباکویی" },
  { shadeCode: "9/8",    shadeName: "Very Light Blonde Tobacco",       nameFa: "بلوند خیلی روشن تنباکویی",        hexColor: "#C7A98F", colorDescription: "very light blonde base with warm tobacco-beige reflect, soft dusty warmth",                 confidence: "high", path: "ai",     brand: "perlacolor", family: "تنباکویی" },
  { shadeCode: "4/7",    shadeName: "Brown Cocoa",                     nameFa: "قهوه‌ای کاکائویی",                hexColor: "#432819", colorDescription: "brown base with deep cocoa-brown reflect, warm chocolate tone",                             confidence: "high", path: "local",  brand: "perlacolor", family: "کاکائویی" },
  { shadeCode: "5/7",    shadeName: "Light Brown Cocoa",               nameFa: "قهوه‌ای روشن کاکائویی",           hexColor: "#623D28", colorDescription: "light brown base with deep cocoa-brown reflect, warm chocolate tone",                       confidence: "high", path: "local",  brand: "perlacolor", family: "کاکائویی" },
  { shadeCode: "6/7",    shadeName: "Dark Blonde Cocoa",               nameFa: "بلوند تیره کاکائویی",             hexColor: "#7D5036", colorDescription: "dark blonde base with deep cocoa-brown reflect, warm chocolate tone",                       confidence: "high", path: "local",  brand: "perlacolor", family: "کاکائویی" },
  { shadeCode: "7/7",    shadeName: "Blonde Cocoa",                    nameFa: "بلوند کاکائویی",                  hexColor: "#9D6748", colorDescription: "blonde base with deep cocoa-brown reflect, warm chocolate tone",                            confidence: "high", path: "ai",     brand: "perlacolor", family: "کاکائویی" },
  { shadeCode: "8/7",    shadeName: "Light Blonde Cocoa",              nameFa: "بلوند روشن کاکائویی",             hexColor: "#B58568", colorDescription: "light blonde base with deep cocoa-brown reflect, warm chocolate tone",                      confidence: "high", path: "ai",     brand: "perlacolor", family: "کاکائویی" },
  { shadeCode: "9/7",    shadeName: "Very Light Blonde Cocoa",         nameFa: "بلوند خیلی روشن کاکائویی",        hexColor: "#C4A18D", colorDescription: "very light blonde base with deep cocoa-brown reflect, warm chocolate tone",                 confidence: "high", path: "ai",     brand: "perlacolor", family: "کاکائویی" },
  { shadeCode: "5/4",    shadeName: "Light Brown Copper",              nameFa: "قهوه‌ای روشن مسی",                hexColor: "#7F3815", colorDescription: "light brown base with warm copper-orange reflect, vibrant metallic glow",                   confidence: "high", path: "local",  brand: "perlacolor", family: "مسی" },
  { shadeCode: "6/4",    shadeName: "Dark Blonde Copper",              nameFa: "بلوند تیره مسی",                  hexColor: "#A2481A", colorDescription: "dark blonde base with warm copper-orange reflect, vibrant metallic glow",                   confidence: "high", path: "local",  brand: "perlacolor", family: "مسی" },
  { shadeCode: "7/4",    shadeName: "Blonde Copper",                   nameFa: "بلوند مسی",                       hexColor: "#CC5C24", colorDescription: "blonde base with warm copper-orange reflect, vibrant metallic glow",                        confidence: "high", path: "ai",     brand: "perlacolor", family: "مسی" },
  { shadeCode: "8/4",    shadeName: "Light Blonde Copper",             nameFa: "بلوند روشن مسی",                  hexColor: "#DC7C4B", colorDescription: "light blonde base with warm copper-orange reflect, vibrant metallic glow",                  confidence: "high", path: "ai",     brand: "perlacolor", family: "مسی" },
  { shadeCode: "9/4",    shadeName: "Very Light Blonde Copper",        nameFa: "بلوند خیلی روشن مسی",             hexColor: "#E39C78", colorDescription: "very light blonde base with warm copper-orange reflect, vibrant metallic glow",             confidence: "high", path: "ai",     brand: "perlacolor", family: "مسی" },
  { shadeCode: "6/44",   shadeName: "Dark Blonde Intense Copper",      nameFa: "بلوند تیره مسی پرقدرت",           hexColor: "#AF390E", colorDescription: "dark blonde base with intense fiery copper reflect, highly saturated orange",               confidence: "high", path: "local",  brand: "perlacolor", family: "مسی پرقدرت" },
  { shadeCode: "7/44",   shadeName: "Blonde Intense Copper",           nameFa: "بلوند مسی پرقدرت",                hexColor: "#DB4A15", colorDescription: "blonde base with intense fiery copper reflect, highly saturated orange",                    confidence: "high", path: "ai",     brand: "perlacolor", family: "مسی پرقدرت" },
  { shadeCode: "8/44",   shadeName: "Light Blonde Intense Copper",     nameFa: "بلوند روشن مسی پرقدرت",           hexColor: "#E96C3E", colorDescription: "light blonde base with intense fiery copper reflect, highly saturated orange",              confidence: "high", path: "ai",     brand: "perlacolor", family: "مسی پرقدرت" },
  { shadeCode: "4/6",    shadeName: "Brown Red",                       nameFa: "قهوه‌ای قرمز",                    hexColor: "#4F160D", colorDescription: "brown base with warm red reflect with deep crimson undertones",                             confidence: "high", path: "local",  brand: "perlacolor", family: "قرمز" },
  { shadeCode: "5/66",   shadeName: "Light Brown Intense Red",         nameFa: "قهوه‌ای روشن قرمز پرقدرت",        hexColor: "#7F0E0A", colorDescription: "light brown base with very intense vivid red reflect, high-impact saturation",              confidence: "high", path: "local",  brand: "perlacolor", family: "قرمز" },
  { shadeCode: "6/66",   shadeName: "Dark Blonde Intense Red",         nameFa: "بلوند تیره قرمز پرقدرت",          hexColor: "#A5120D", colorDescription: "dark blonde base with very intense vivid red reflect, high-impact saturation",              confidence: "high", path: "local",  brand: "perlacolor", family: "قرمز" },
  { shadeCode: "7/66",   shadeName: "Blonde Intense Red",              nameFa: "بلوند قرمز پرقدرت",               hexColor: "#D11A14", colorDescription: "blonde base with very intense vivid red reflect, high-impact saturation",                   confidence: "high", path: "ai",     brand: "perlacolor", family: "قرمز" },
  { shadeCode: "4/5",    shadeName: "Brown Mahogany",                  nameFa: "قهوه‌ای ماهاگونی",                hexColor: "#471D15", colorDescription: "brown base with mahogany red-violet reflect, warm wine undertones",                         confidence: "high", path: "local",  brand: "perlacolor", family: "ماهاگونی" },
  { shadeCode: "5/5",    shadeName: "Light Brown Mahogany",            nameFa: "قهوه‌ای روشن ماهاگونی",           hexColor: "#6B2C1F", colorDescription: "light brown base with mahogany red-violet reflect, warm wine undertones",                   confidence: "high", path: "local",  brand: "perlacolor", family: "ماهاگونی" },
  { shadeCode: "6/5",    shadeName: "Dark Blonde Mahogany",            nameFa: "بلوند تیره ماهاگونی",             hexColor: "#8A3928", colorDescription: "dark blonde base with mahogany red-violet reflect, warm wine undertones",                   confidence: "high", path: "local",  brand: "perlacolor", family: "ماهاگونی" },
  { shadeCode: "4/2",    shadeName: "Brown Irisé",                     nameFa: "قهوه‌ای بنفش",                    hexColor: "#422433", colorDescription: "brown base with violet-rosé reflect, cool iridescent shimmer",                              confidence: "high", path: "local",  brand: "perlacolor", family: "بنفش (ایریزه)" },
  { shadeCode: "5/2",    shadeName: "Light Brown Irisé",               nameFa: "قهوه‌ای روشن بنفش",               hexColor: "#5F354A", colorDescription: "light brown base with violet-rosé reflect, cool iridescent shimmer",                        confidence: "high", path: "local",  brand: "perlacolor", family: "بنفش (ایریزه)" },
  { shadeCode: "6/2",    shadeName: "Dark Blonde Irisé",               nameFa: "بلوند تیره بنفش",                 hexColor: "#77455E", colorDescription: "dark blonde base with violet-rosé reflect, cool iridescent shimmer",                        confidence: "high", path: "local",  brand: "perlacolor", family: "بنفش (ایریزه)" },
  { shadeCode: "7/2",    shadeName: "Blonde Irisé",                    nameFa: "بلوند بنفش",                      hexColor: "#955A78", colorDescription: "blonde base with violet-rosé reflect, cool iridescent shimmer",                             confidence: "high", path: "ai",     brand: "perlacolor", family: "بنفش (ایریزه)" },
  { shadeCode: "11/0",   shadeName: "Super Blonde Natural",            nameFa: "سوپر بلوند طبیعی",                hexColor: "#E4DBC8", colorDescription: "super lightening natural blonde, soft beige result",                                        confidence: "high", path: "ai",     brand: "perlacolor", family: "سوپر روشن‌کننده" },
  { shadeCode: "11/1",   shadeName: "Super Blonde Ash",                nameFa: "سوپر بلوند خاکستری",              hexColor: "#DDDAD4", colorDescription: "super lightening ash blonde, cool neutralising result",                                     confidence: "high", path: "ai",     brand: "perlacolor", family: "سوپر روشن‌کننده" },
  { shadeCode: "11/2",   shadeName: "Super Blonde Irisé",              nameFa: "سوپر بلوند بنفش",                 hexColor: "#DED3D9", colorDescription: "super lightening violet blonde, cool pearl-violet result",                                  confidence: "high", path: "ai",     brand: "perlacolor", family: "سوپر روشن‌کننده" },
  { shadeCode: "12/1",   shadeName: "Extra Blonde Ash",                nameFa: "اکسترا بلوند خاکستری",            hexColor: "#E6E4E0", colorDescription: "extra super lightening ash blonde, icy cool result",                                        confidence: "high", path: "ai",     brand: "perlacolor", family: "سوپر روشن‌کننده" },
  { shadeCode: "12/9",   shadeName: "Extra Blonde Pearl",              nameFa: "اکسترا بلوند صدفی",               hexColor: "#E9E6E2", colorDescription: "extra super lightening pearl blonde, luminous shimmer",                                     confidence: "high", path: "ai",     brand: "perlacolor", family: "سوپر روشن‌کننده" },
  { shadeCode: "12/11",  shadeName: "Extra Blonde Matt",               nameFa: "اکسترا بلوند مات",                hexColor: "#E5E4E1", colorDescription: "extra super lightening matt blonde, strongly anti-yellow",                                  confidence: "high", path: "ai",     brand: "perlacolor", family: "سوپر روشن‌کننده" },
  { shadeCode: "12/2",   shadeName: "Extra Blonde Irisé",              nameFa: "اکسترا بلوند بنفش",               hexColor: "#E7DFE4", colorDescription: "extra super lightening violet blonde, icy pearl-violet",                                    confidence: "high", path: "ai",     brand: "perlacolor", family: "سوپر روشن‌کننده" },
];

/** What the UI should call a shade — Persian name when we have one. */
export function shadeLabel(shade: ShadeInfo): string {
  return shade.nameFa ?? shade.shadeName;
}
